import { ParameterType } from '@/core/types'
const xHeight = 500
const ascender = 800
const capitalHeight = 750
const width = 360
const capitalWidth = 500
const descender = -200

const symbols_en = [
  {
    name: '!',
    script_file_name: 'unicode_0x21_!.js',
    params: [
      {
        name: 'h1',
        value: 506,
        min: 0,
        max: 1000,
        step: 1,
        default: 506,
      },
      {
        name: 'h2',
        value: 135,
        min: 0,
        max: 1000,
        step: 1,
        default: 135,
      },
      {
        name: 'r1',
        value: 1.78,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.78,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '"',
    script_file_name: 'unicode_0x22_".js',
    params: [
      {
        name: 'h1',
        value: 180,
        min: 0,
        max: 1000,
        step: 1,
        default: 180,
      },
      {
        name: 'w1',
        value: 200,
        min: 0,
        max: 1000,
        step: 1,
        default: 200,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '#',
    script_file_name: 'unicode_0x23.js',
    params: [
      {
        name: 'h1',
        value: 270,
        min: 0,
        max: 1000,
        step: 1,
        default: 270,
      },
      {
        name: 'h2',
        value: 730,
        min: 0,
        max: 1000,
        step: 1,
        default: 730,
      },
      {
        name: 'w1',
        value: 730,
        min: 0,
        max: 1000,
        step: 1,
        default: 730,
      },
      {
        name: 'w2',
        value: 270,
        min: 0,
        max: 1000,
        step: 1,
        default: 270,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '$',
    script_file_name: 'unicode_0x24_$.js',
    params: [
      {
        name: 'h1',
        value: 600,
        min: 0,
        max: 1000,
        step: 1,
        default: 600,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
      {
        name: 'h3',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
      {
        name: 'h4',
        value: 281,
        min: 0,
        max: 1000,
        step: 1,
        default: 281,
      },
      {
        name: 'w1',
        value: 400,
        min: 0,
        max: 1000,
        step: 1,
        default: 400,
      },
      {
        name: 'w2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
      {
        name: 'c1',
        value: 0.35,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.35,
      },
      {
        name: 'c2',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.5,
      },
      {
        name: 'c3',
        value: 0.67,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.67,
      },
      {
        name: 'c4',
        value: 0.66,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.66,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '%',
    script_file_name: 'unicode_0x25_%.js',
    params: [
      {
        name: 'h1',
        value: 370,
        min: 0,
        max: 1000,
        step: 1,
        default: 370,
      },
      {
        name: 'h2',
        value: 575,
        min: 0,
        max: 1000,
        step: 1,
        default: 575,
      },
      {
        name: 'w1',
        value: 286,
        min: 0,
        max: 1000,
        step: 1,
        default: 286,
      },
      {
        name: 'w2',
        value: 68,
        min: 0,
        max: 1000,
        step: 1,
        default: 68,
      },
      {
        name: 'r1',
        value: 80,
        min: 0,
        max: 200,
        step: 1,
        default: 80,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: "'",
    script_file_name: "unicode_0x27_'.js",
    params: [
      {
        name: 'h1',
        value: 180,
        min: 0,
        max: 1000,
        step: 1,
        default: 180,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '(',
    script_file_name: 'unicode_0x28_(.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.8,
      },
      {
        name: 'w1',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: ')',
    script_file_name: 'unicode_0x29_).js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.8,
      },
      {
        name: 'w1',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '+',
    script_file_name: 'unicode_0x2b_+.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.5,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.5,
      },
      {
        name: 'w1',
        value: capitalHeight * 0.5,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.5,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: ',',
    script_file_name: 'unicode_0x2c_,.js',
    params: [
      {
        name: 'h1',
        value: 230,
        min: 0,
        max: 1000,
        step: 1,
        default: 230,
      },
      {
        name: 'h2',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'w1',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 55,
        min: 50,
        max: 300,
        step: 1,
        default: 55,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '-',
    script_file_name: 'unicode_0x2d_-.js',
    params: [
      {
        name: 'w1',
        value: capitalHeight * 0.5,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.5,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '.',
    script_file_name: 'unicode_0x2e_..js',
    params: [
      {
        name: 'r1',
        value: 1.78,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.78,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '/',
    script_file_name: 'unicode_0x2f.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.5,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.5,
      },
      {
        name: 'w1',
        value: capitalHeight * 0.2,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.2,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: ':',
    script_file_name: 'unicode_0x3a_:.js',
    params: [
      {
        name: 'h1',
        value: 286,
        min: 0,
        max: 1000,
        step: 1,
        default: 286,
      },
      {
        name: 'r1',
        value: 1.78,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.78,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: ';',
    script_file_name: 'unicode_0x3b_;.js',
    params: [
      {
        name: 'h1',
        value: 286,
        min: 0,
        max: 1000,
        step: 1,
        default: 286,
      },
      {
        name: 'h2',
        value: 190,
        min: 0,
        max: 1000,
        step: 1,
        default: 190,
      },
      {
        name: 'h3',
        value: 190,
        min: 0,
        max: 1000,
        step: 1,
        default: 190,
      },
      {
        name: 'w1',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 60 * 1.78 / 2 - 30,
        min: 20,
        max: 300,
        step: 1,
        default: 60 * 1.78 / 2 - 30,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '<',
    script_file_name: 'unicode_0x3c_<.js',
    params: [
      {
        name: 'h1',
        value: 450,
        min: 0,
        max: 1000,
        step: 1,
        default: 450,
      },
      {
        name: 'w1',
        value: 600,
        min: 0,
        max: 1000,
        step: 1,
        default: 600,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '=',
    script_file_name: 'unicode_0x3d_=.js',
    params: [
      {
        name: 'h1',
        value: 263,
        min: 0,
        max: 1000,
        step: 1,
        default: 263,
      },
      {
        name: 'w1',
        value: 600,
        min: 0,
        max: 1000,
        step: 1,
        default: 600,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '>',
    script_file_name: 'unicode_0x3e_>.js',
    params: [
      {
        name: 'h1',
        value: 450,
        min: 0,
        max: 1000,
        step: 1,
        default: 450,
      },
      {
        name: 'w1',
        value: 600,
        min: 0,
        max: 1000,
        step: 1,
        default: 600,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '?',
    script_file_name: 'unicode_0x3f.js',
    params: [
      {
        name: 'h1',
        value: 285,
        min: 0,
        max: 1000,
        step: 1,
        default: 285,
      },
      {
        name: 'h2',
        value: 109,
        min: 0,
        max: 1000,
        step: 1,
        default: 109,
      },
      {
        name: 'h3',
        value: 132,
        min: 0,
        max: 1000,
        step: 1,
        default: 132,
      },
      {
        name: 'h4',
        value: 122,
        min: 0,
        max: 1000,
        step: 1,
        default: 122,
      },
      {
        name: 'h5',
        value: 156,
        min: 0,
        max: 1000,
        step: 1,
        default: 156,
      },
      {
        name: 'w1',
        value: 356,
        min: 0,
        max: 1000,
        step: 1,
        default: 356,
      },
      {
        name: 'w2',
        value: 201,
        min: 0,
        max: 1000,
        step: 1,
        default: 201,
      },
      {
        name: 'w3',
        value: 4,
        min: 0,
        max: 1000,
        step: 1,
        default: 4,
      },
      {
        name: 'c1',
        value: 0.51,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.51,
      },
      {
        name: 'c2',
        value: 0.79,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.79,
      },
      {
        name: 'r1',
        value: 1.5,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.5,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '{',
    script_file_name: 'unicode_0x7b_{.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight,
      },
      {
        name: 'w1',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
      {
        name: 'w2',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
      {
        name: 'c1',
        value: 0.68,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.68,
      },
      {
        name: 'c2',
        value: 0.68,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.68,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '|',
    script_file_name: 'unicode_0x7c_|.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '}',
    script_file_name: 'unicode_0x7d_}.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight,
      },
      {
        name: 'w1',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
      {
        name: 'w2',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
      {
        name: 'c1',
        value: 0.68,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.68,
      },
      {
        name: 'c2',
        value: 0.68,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.68,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '*',
    script_file_name: 'unicode_0x2a_*.js',
    params: [
      {
        name: 'r1',
        value: 180,
        min: 50,
        max: 500,
        step: 1,
        default: 180,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  // {
  //   name: '&',
  //   script_file_name: 'unicode_0x26_&.js',
  //   params: [
  //     {
  //       name: 'h1',
  //       value: 750,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 750,
  //     },
  //     {
  //       name: 'h2',
  //       value: 233,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 233,
  //     },
  //     {
  //       name: 'h3',
  //       value: 366,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 366,
  //     },
  //     {
  //       name: 'w3',
  //       value: 316,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 316,
  //     },
  //     {
  //       name: 'w2',
  //       value: 546,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 546,
  //     },
  //     {
  //       name: 'w1',
  //       value: 449,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 449,
  //     },
  //     {
  //       name: 'c1',
  //       value: 0.34,
  //       min: 0,
  //       max: 1,
  //       step: 0.01,
  //       default: 0.34,
  //     },
  //     {
  //       name: 'c2',
  //       value: 0.40,
  //       min: 0,
  //       max: 1,
  //       step: 0.01,
  //       default: 0.40,
  //     },
  //     {
  //       name: 'h4',
  //       value: 243,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 243,
  //     },
  //     {
  //       name: 'h5',
  //       value: 294,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 294,
  //     },
  //     {
  //       name: 'w4',
  //       value: 58,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 58,
  //     },
  //   ],
  //   globalParams: [
  //     {
  //       name: '字重',
  //       value: 40,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 40,
  //     },
  //   ],
  // },
  // {
  //   name: '@',
  //   script_file_name: 'unicode_0x40_@.js',
  //   params: [
  //     {
  //       name: 'h1',
  //       value: capitalHeight * 0.5,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: capitalHeight * 0.5,
  //     },
  //     {
  //       name: 'h2',
  //       value: capitalHeight * 0.15,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: capitalHeight * 0.15,
  //     },
  //     {
  //       name: 'w1',
  //       value: width,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: width,
  //     },
  //     {
  //       name: 'w2',
  //       value: width * 0.2,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: width * 0.2,
  //     },
  //     {
  //       name: 'r1',
  //       value: capitalHeight * 0.5,
  //       min: 50,
  //       max: 500,
  //       step: 1,
  //       default: capitalHeight * 0.5,
  //     },
  //   ],
  //   globalParams: [
  //     {
  //       name: '字重',
  //       value: 40,
  //       min: 0,
  //       max: 1000,
  //       step: 1,
  //       default: 40,
  //     },
  //   ],
  // },
]

const symbols_zh = [
  {
    name: '《',
    script_file_name: 'unicode_0x300a_《.js',
    params: [
      {
        name: 'h1',
        value: 750,
        min: 0,
        max: 1000,
        step: 1,
        default: 750,
      },
      {
        name: 'w1',
        value: 140,
        min: 0,
        max: 1000,
        step: 1,
        default: 140,
      },
      {
        name: 'w2',
        value: 150,
        min: 0,
        max: 1000,
        step: 1,
        default: 150,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '》',
    script_file_name: 'uncode_0x300b_》.js',
    params: [
      {
        name: 'h1',
        value: 750,
        min: 0,
        max: 1000,
        step: 1,
        default: 750,
      },
      {
        name: 'w1',
        value: 140,
        min: 0,
        max: 1000,
        step: 1,
        default: 140,
      },
      {
        name: 'w2',
        value: 150,
        min: 0,
        max: 1000,
        step: 1,
        default: 150,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '，',
    script_file_name: 'unicode_0xff0c_，.js',
    params: [
      {
        name: 'h1',
        value: 230,
        min: 0,
        max: 1000,
        step: 1,
        default: 230,
      },
      {
        name: 'h2',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'w1',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 55,
        min: 50,
        max: 300,
        step: 1,
        default: 55,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '！',
    script_file_name: 'unicode_0xff01_！.js',
    params: [
      {
        name: 'h1',
        value: 506,
        min: 0,
        max: 1000,
        step: 1,
        default: 506,
      },
      {
        name: 'h2',
        value: 135,
        min: 0,
        max: 1000,
        step: 1,
        default: 135,
      },
      {
        name: 'r1',
        value: 1.78,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.78,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '：',
    script_file_name: 'unicode_0xff1a_：.js',
    params: [
      {
        name: 'h1',
        value: 286,
        min: 0,
        max: 1000,
        step: 1,
        default: 286,
      },
      {
        name: 'r1',
        value: 1.78,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.78,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '；',
    script_file_name: 'unicode_0xff1b_；.js',
    params: [
      {
        name: 'h1',
        value: 286,
        min: 0,
        max: 1000,
        step: 1,
        default: 286,
      },
      {
        name: 'h2',
        value: 190,
        min: 0,
        max: 1000,
        step: 1,
        default: 190,
      },
      {
        name: 'h3',
        value: 190,
        min: 0,
        max: 1000,
        step: 1,
        default: 190,
      },
      {
        name: 'w1',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 60 * 1.78 / 2 - 30,
        min: 20,
        max: 300,
        step: 1,
        default: 60 * 1.78 / 2 - 30,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '？',
    script_file_name: 'unicode_0xff1f_？.js',
    params: [
      {
        name: 'h1',
        value: 285,
        min: 0,
        max: 1000,
        step: 1,
        default: 285,
      },
      {
        name: 'h2',
        value: 109,
        min: 0,
        max: 1000,
        step: 1,
        default: 109,
      },
      {
        name: 'h3',
        value: 132,
        min: 0,
        max: 1000,
        step: 1,
        default: 132,
      },
      {
        name: 'h4',
        value: 122,
        min: 0,
        max: 1000,
        step: 1,
        default: 122,
      },
      {
        name: 'h5',
        value: 156,
        min: 0,
        max: 1000,
        step: 1,
        default: 156,
      },
      {
        name: 'w1',
        value: 356,
        min: 0,
        max: 1000,
        step: 1,
        default: 356,
      },
      {
        name: 'w2',
        value: 201,
        min: 0,
        max: 1000,
        step: 1,
        default: 201,
      },
      {
        name: 'w3',
        value: 4,
        min: 0,
        max: 1000,
        step: 1,
        default: 4,
      },
      {
        name: 'c1',
        value: 0.51,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.51,
      },
      {
        name: 'c2',
        value: 0.79,
        min: 0,
        max: 1,
        step: 0.01,
        default: 0.79,
      },
      {
        name: 'r1',
        value: 1.5,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.5,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '”',
    script_file_name: 'unicode_0x201d_”.js',
    params: [
      {
        name: 'h1',
        value: 262,
        min: 0,
        max: 1000,
        step: 1,
        default: 262,
      },
      {
        name: 'h2',
        value: 166,
        min: 0,
        max: 1000,
        step: 1,
        default: 166,
      },
      {
        name: 'w1',
        value: 290,
        min: 0,
        max: 1000,
        step: 1,
        default: 290,
      },
      {
        name: 'w2',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 55,
        min: 50,
        max: 300,
        step: 1,
        default: 55,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '“',
    script_file_name: 'unicode_0x201c_“.js',
    params: [
      {
        name: 'h1',
        value: 262,
        min: 0,
        max: 1000,
        step: 1,
        default: 262,
      },
      {
        name: 'h2',
        value: 166,
        min: 0,
        max: 1000,
        step: 1,
        default: 166,
      },
      {
        name: 'w1',
        value: 290,
        min: 0,
        max: 1000,
        step: 1,
        default: 290,
      },
      {
        name: 'w2',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 55,
        min: 50,
        max: 300,
        step: 1,
        default: 55,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '「',
    script_file_name: 'unicode_0x300c_「.js',
    params: [
      {
        name: 'h1',
        value: 470,
        min: 0,
        max: 1000,
        step: 1,
        default: 470,
      },
      {
        name: 'w1',
        value: 260,
        min: 0,
        max: 1000,
        step: 1,
        default: 260,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '」',
    script_file_name: 'unicode_0x300d_」.js',
    params: [
      {
        name: 'h1',
        value: 470,
        min: 0,
        max: 1000,
        step: 1,
        default: 470,
      },
      {
        name: 'w1',
        value: 260,
        min: 0,
        max: 1000,
        step: 1,
        default: 260,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '‘',
    script_file_name: 'unicode_0x2018.js',
    params: [
      {
        name: 'h1',
        value: 230,
        min: 0,
        max: 1000,
        step: 1,
        default: 230,
      },
      {
        name: 'h2',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'w1',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 55,
        min: 50,
        max: 300,
        step: 1,
        default: 55,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '’',
    script_file_name: 'unicode_0x2019.js',
    params: [
      {
        name: 'h1',
        value: 230,
        min: 0,
        max: 1000,
        step: 1,
        default: 230,
      },
      {
        name: 'h2',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'w1',
        value: 114,
        min: 0,
        max: 1000,
        step: 1,
        default: 114,
      },
      {
        name: 'r1',
        value: 55,
        min: 50,
        max: 300,
        step: 1,
        default: 55,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '…',
    script_file_name: 'unicode_0x2026_….js',
    params: [
      {
        name: 'w1',
        value: width,
        min: 0,
        max: 1000,
        step: 1,
        default: width,
      },
      {
        name: 'r1',
        value: 1.5,
        min: 1,
        max: 2,
        step: 0.1,
        default: 1.5,
      }
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '—',
    script_file_name: 'unicode_0x2027_—.js',
    params: [
      {
        name: 'w1',
        value: width * 1.5,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 1.5,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '【',
    script_file_name: 'unicode_0x3010_【.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.8,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
      {
        name: 'w1',
        value: width * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.8,
      },
      {
        name: 'w2',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '】',
    script_file_name: 'unicode_0x3011_】.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.8,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
      {
        name: 'w1',
        value: width * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.8,
      },
      {
        name: 'w2',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '、',
    script_file_name: 'unicode_0x3001_、.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.3,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.3,
      },
      {
        name: 'w1',
        value: width * 0.5,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.5,
      },
      {
        name: 'bendCursor',
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.1,
        default: 0.5,
      },
      {
        name: 'bendDegree',
        value: 50,
        min: 0,
        max: 200,
        step: 1,
        default: 50,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '。',
    script_file_name: 'unicode_0x3002_。.js',
    params: [
      {
        name: 'r1',
        value: 100,
        min: 50,
        max: 300,
        step: 1,
        default: 100,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '~',
    script_file_name: 'unicode_0xff5e_~.js',
    params: [
      {
        name: 'h1',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
      {
        name: 'w1',
        value: width * 1.5,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 1.5,
      },
      {
        name: 'w2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
      {
        name: 'w3',
        value: width * 0.35,
        min: 0,
        max: 1000,
        step: 1,
        default: width * 0.35,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '（',
    script_file_name: 'unicode_0xff08_（.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.8,
      },
      {
        name: 'w1',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '）',
    script_file_name: 'unicode_0xff09_）.js',
    params: [
      {
        name: 'h1',
        value: capitalHeight * 0.8,
        min: 0,
        max: 1000,
        step: 1,
        default: capitalHeight * 0.8,
      },
      {
        name: 'w1',
        value: 120,
        min: 0,
        max: 1000,
        step: 1,
        default: 120,
      },
      {
        name: 'h2',
        value: 80,
        min: 0,
        max: 1000,
        step: 1,
        default: 80,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
  {
    name: '￥',
    script_file_name: 'unicode_0xffe5_￥.js',
    params: [
      {
        name: 'h1',
        value: 300,
        min: 0,
        max: 1000,
        step: 1,
        default: 300,
      },
      {
        name: 'h2',
        value: 156,
        min: 0,
        max: 1000,
        step: 1,
        default: 156,
      },
      {
        name: 'h3',
        value: 200,
        min: 0,
        max: 1000,
        step: 1,
        default: 200,
      },
      {
        name: 'w1',
        value: 471,
        min: 0,
        max: 1000,
        step: 1,
        default: 471,
      },
      {
        name: 'w2',
        value: 393,
        min: 0,
        max: 1000,
        step: 1,
        default: 393,
      },
    ],
    globalParams: [
      {
        name: '字重',
        value: 60,
        min: 0,
        max: 1000,
        step: 1,
        default: 60,
      },
    ],
  },
]
export {
  symbols_en,
  symbols_zh,
}