/**
 * Generate RSA-4096 key pair for FP file encryption.
 * Run: npm run generate-keys
 *
 * Outputs:
 *   src/core/encryption/publicKey.ts — public key (commit to repo)
 *   src-tauri/resources/.keydata  — obfuscated private key (gitignored)
 *   public/.keydata               — obfuscated private key (gitignored)
 */
import { generateKeyPairSync, createHash } from 'node:crypto'
import { writeFileSync, mkdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const OBFUSCATION_SEED = 'com.fontplayer.app.encryption.v1'

function deriveKeyMaterial(seed: string, length: number): Buffer {
  const hash = createHash('sha256').update(seed).digest()
  const result = Buffer.alloc(length)
  for (let i = 0; i < length; i++) {
    result[i] = hash[i % hash.length]!
  }
  return result
}

function obfuscate(data: Buffer): string {
  const keyMaterial = deriveKeyMaterial(OBFUSCATION_SEED, data.length)
  const result = Buffer.alloc(data.length)
  for (let i = 0; i < data.length; i++) {
    result[i] = data[i]! ^ keyMaterial[i]!
  }
  return result.toString('base64')
}

console.log('Generating RSA-4096 key pair...')

const { publicKey, privateKey } = generateKeyPairSync('rsa', {
  modulusLength: 4096,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'der' },
})

// Write public key as TypeScript module
const publicKeyTs = `// Auto-generated by scripts/generate-keys.ts — DO NOT EDIT
export const PUBLIC_KEY_PEM = ${JSON.stringify(publicKey)};
`
const encryptionDir = join(ROOT, 'src', 'core', 'encryption')
mkdirSync(encryptionDir, { recursive: true })
writeFileSync(join(encryptionDir, 'publicKey.ts'), publicKeyTs)
console.log('  ✓ Public key written to src/core/encryption/publicKey.ts')

// Obfuscate and write private key
const obfuscated = obfuscate(privateKey)

// Desktop (Tauri resource)
const resourcesDir = join(ROOT, 'src-tauri', 'resources')
mkdirSync(resourcesDir, { recursive: true })
writeFileSync(join(resourcesDir, '.keydata'), obfuscated)
console.log('  ✓ Obfuscated private key written to src-tauri/resources/.keydata')

// Web (public/ asset)
const publicDir = join(ROOT, 'public')
mkdirSync(publicDir, { recursive: true })
writeFileSync(join(publicDir, '.keydata'), obfuscated)
console.log('  ✓ Obfuscated private key written to public/.keydata')

console.log('\nKey generation complete!')
console.log('  Remember: .keydata files are gitignored — each developer must run this script.')
